default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: foodfinder_development

test:
  <<: *default
  database: foodfinder_test

production:
  <<: *default
  databse: foodfinder_production
